const stories = {
    conhecemos: "Talvez eu não seja a melhor em puxar conversa... mas naquele dia, mesmo sem saber o que dizer, eu tentei. E tudo bem não ter sido ali que começamos de verdade, porque se tem uma coisa que eu não faria, é desistir fácil de você.",
    gostar: "A gente já tava conversando e tal, mas tudo ainda ia devagar… eu nem sabia se você queria algo comigo, então fui indo no seu tempo, até onde você deixava. Mas aquele dia ficou marcado pra mim — foi quando você teve sua promoção… e eu também. Você tava tão feliz, tão animada, e eu fiquei feliz por você também, de verdade. Sabia o quanto você se dedicava à staff, eu via tudo, só ficava observando quietinha kkk. Aí você e a Hera fizeram aquela festa... e desde então, eu nunca mais deixei de te seguir nas festas kkk.",
    Farol: "O farol ficou marcado na nossa história, porque foi ali que a gente teve a nossa primeira conversa de verdade — sobre tudo. Foi onde eu desabafei o que queria em um relacionamento, e você também abriu seu coração. A gente ficou lá, falando de coisas aleatórias, e tudo foi tão leve... Estar com você sempre foi assim, né? Leve. E ainda é. Sempre que volto lá, penso em você. Mesmo quando não estamos juntas, é como se aquele lugar me deixasse mais perto de ti, de alguma forma.",
    Aniversario: "No meu aniversário, eu tava meio revoltada... Tive que ir pra Porangaba, você tava sem internet, então já imaginei que a gente só conseguiria se falar por mensagem. E pra piorar, parecia que a galera do RP tinha esquecido que dia era... fui me ocupando durante o dia, já que a gente tinha combinado de ver um filme. Aí, do nada, o Anorak começa a me chamar, insistindo que eu ajudasse com um negócio da Hana — e eu nem queria entrar! Na minha cabeça: Logo hoje ele vem com b.o? E você, mesmo sem internet, roteando do celular só pra estar ali comigo… Quando a gente chegou na trilha… surpresa: uma festa inteira organizada por você, pra mim. Mesmo sem conexão, sem estrutura, você fez tudo acontecer. Eu juro, eu não sabia onde enfiar a cara, só queria te abraçar e te encher de beijos… se não fosse pela distância kkk.",
    termino: "Logo depois da inauguração do Balneário, comecei a te sentir um pouco distante. Mas eu entendia — era muita correria por lá, e tentei ficar tranquila, te dar o seu espaço. Aí você pediu pra sair do Bahamas e me chamou pra conversar… ali eu já senti o que vinha. Tentei conversar contigo, queria muito que a gente não terminasse. A gente sempre falou sobre ter algo fora do RP também, então pra mim não era um problema a gente se afastar um pouco lá dentro, contanto que continuássemos juntas. Mas eu entendi. Entendi os motivos que te fizeram se afastar… e tudo bem. Era o que você sentia, o que achou certo naquele momento. Eu tentei seguir meu caminho, juro. Mas você não saía da minha cabeça. Volta e meia, eu assistia os clipes nossos… e meu coração apertava.",
    reconciliacao: "Tantas coisas aconteceram nesse tempo… sinceramente, eu achava que você não ia mais me querer além da amizade que a gente acabou construindo. Mas a verdade é que eu nunca deixei de sentir ciúmes de você — só não falava, e sei que isso não era o certo da minha parte. Tipo aquele dia que você me contou que ia em um rolê da faculdade… nossa, eu fiquei muito brava! Fiz de tudo pra te convencer a não ir, porque eu sabia como esses rolês são, e só de imaginar você com outra pessoa… não dava. Mas tudo bem, isso ficou no passado. A gente voltou a conversar, você decidiu buscar o balde que tinha chutado kkkkk — e olha, eu só tenho a agradecer por isso. Sério.",
    pedido: "Amor, eu sei que você tava tímida pra fazer o pedido, e que não sabia muito bem como fazer… Mas só quero que saiba: foi lindo. E eu amei. De verdade. Não importa se foi simples, nervoso ou cheio de dúvidas — o que importa é que foi com você. E isso, pra mim, já fez tudo ser perfeito.",
    motivos: "Meu amor, tudo o que tenho vivido nesses últimos tempos contigo tem sido incrível. Te amo imensamente, e mesmo sem perceber, você foi chegando de mansinho e se tornando meu tudo. Quando falo sobre meus planos, eu pensava que seria sozinha, mas agora tudo mudou. Eu realmente não planejava me relacionar novamente depois do que passei e do quanto me machuquei com o fim de minha antiga relação. Mas quando ouvi a sua voz naquela reunião, algo me chamou atenção... o jeito que você falou, o tom, o carinho. Algo me dizia que eu precisava ir atrás de você, e foi o que fiz. Fomos nos conhecendo, e eu fui me apaixonando, não só pelo seu jeito, mas também pela leveza e harmonia que encontramos juntos. O que sinto por ti é único, e você me tem mostrado que amar não precisa de inseguranças ou brigas. Você é a pessoa mais incrível que já conheci, e estar com você me faz querer ser melhor a cada dia para te merecer. Não sou de fazer planos, mas pela primeira vez, vou deixá-los para criar contigo. Vou deixar de tentar controlar tudo e, aos poucos, irei aprender a viver o momento. Os planos que quero fazer são simples: passar mais tempo contigo, viver para te ver sorrir e construir nosso caminho juntos. O futuro? Esse vamos deixar para construir aos poucos, conversando e ajustando o que é melhor para nós dois."
  };
  
  function showStory(key) {
    const box = document.getElementById('story-box');
    box.innerText = stories[key];
    box.style.display = 'block';
  }
  